language: ruby
sudo: false
rvm:
  - 2.3.1

env:
  - 'RAILS_VERSION=5.0.0.1'

matrix:
  include:
    - rvm: 2.3.1
      env: 'RAILS_VERSION=4.2.7.1'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
